### ISSUE TITLE
בדיקת ה fetures של  המתחרים השונים

### ISSUE THREAD

**Issue by ordaniel888** [omerfurman/iclub#2]
יש לגלוש באתרי המתחרים כמו חבר,גרופון וכדומה.
המטרה היא למצוא בכל אחד מהם את הנקודות החזקות והחלשות בקונספט ובעיצוב.
ומתוך המידע הזה להסיק:
-מה הfetures שאנחנו רוצים לקחת מהם
-מה הfetures שאנחנו רוצים להימנע מהם
-איזה fetures ייחדו את האפליקציה שלנו לעומתם ויעניקו לנו יתרון מולם

**Comment by omerfurman** [comment]
בוצע
